# Generated by Django 3.1.1 on 2020-10-03 03:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pangkat',
            fields=[
                ('pangkat_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('nomer_urut', models.PositiveSmallIntegerField()),
                ('pangkat_name', models.CharField(max_length=20)),
                ('golongan', models.CharField(max_length=5)),
            ],
        ),
    ]
