# Generated by Django 3.1.1 on 2020-10-03 03:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pegawai', '0002_auto_20201003_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pangkat',
            name='nomer_urut',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
