# Generated by Django 3.1.1 on 2020-10-03 03:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pegawai', '0003_auto_20201003_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pangkat',
            name='pangkat_name',
            field=models.CharField(max_length=25),
        ),
    ]
