# Generated by Django 3.1.1 on 2020-10-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pegawai', '0004_auto_20201003_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pangkat',
            name='pangkat_name',
            field=models.CharField(max_length=30),
        ),
    ]
