# Generated by Django 3.1.1 on 2020-10-03 04:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pegawai', '0006_auto_20201003_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pangkat',
            name='pangkat_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
