# Generated by Django 3.1.1 on 2020-10-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pegawai', '0007_auto_20201003_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('pegawai_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('pangkat', models.CharField(max_length=40)),
                ('nip', models.IntegerField()),
            ],
        ),
    ]
