# Generated by Django 3.1.1 on 2020-10-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0008_auto_20201011_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
