# Generated by Django 3.1.1 on 2020-10-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0009_customer_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default=123, upload_to=''),
            preserve_default=False,
        ),
    ]
