# Generated by Django 3.1.1 on 2020-10-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0010_auto_20201012_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
