# Generated by Django 3.1.4 on 2021-01-26 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bagian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Golongan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gol', models.CharField(max_length=5)),
                ('pangkat', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Jabatan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=20)),
                ('nama', models.CharField(max_length=50)),
                ('bagian', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bagian_pegawai', to='nominatif.bagian')),
                ('golongan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='golongan_pegawai', to='nominatif.golongan')),
                ('jabatan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='jabatan_pegawai', to='nominatif.jabatan')),
            ],
        ),
    ]
