# Generated by Django 3.1.4 on 2021-02-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominatif', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jabatan',
            name='nama',
            field=models.CharField(max_length=70),
        ),
    ]
