# Generated by Django 3.1.4 on 2020-12-29 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('absensi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peserta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('nip', models.CharField(max_length=20)),
                ('jabatan', models.CharField(max_length=50)),
                ('unit_kerja', models.CharField(max_length=255)),
                ('rapat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peserta_agenda', to='absensi.rapat')),
            ],
        ),
    ]
