# Generated by Django 3.1.4 on 2021-01-26 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peserta', '0002_bagian_golongan_jabatan_pegawai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pegawai',
            name='bagian',
        ),
        migrations.RemoveField(
            model_name='pegawai',
            name='golongan',
        ),
        migrations.RemoveField(
            model_name='pegawai',
            name='jabatan',
        ),
        migrations.DeleteModel(
            name='Bagian',
        ),
        migrations.DeleteModel(
            name='Golongan',
        ),
        migrations.DeleteModel(
            name='Jabatan',
        ),
        migrations.DeleteModel(
            name='Pegawai',
        ),
    ]
