# Generated by Django 3.1.4 on 2021-01-30 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0001_initial'),
        ('peserta', '0003_auto_20210126_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peserta',
            name='rapat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peserta_rapat', to='absensi.rapat'),
        ),
    ]
