# Generated by Django 3.1.4 on 2021-02-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peserta', '0004_auto_20210130_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='peserta',
            name='no_hp',
            field=models.CharField(default=0, max_length=13),
            preserve_default=False,
        ),
    ]
