# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-29 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sbu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provinsi', models.CharField(max_length=100)),
                ('uang_harian', models.CharField(max_length=100)),
            ],
        ),
    ]
