# Generated by Django 3.1.1 on 2020-10-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sbu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sbu',
            name='id',
        ),
        migrations.AddField(
            model_name='sbu',
            name='sbu_id',
            field=models.CharField(default=1, editable=False, max_length=40, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
