# Generated by Django 3.1.4 on 2020-12-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rapat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=5)),
                ('tanggal', models.DateTimeField()),
                ('meeting_id', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('pimpinan_rapat', models.CharField(max_length=50)),
                ('agenda', models.TextField()),
            ],
        ),
    ]
