# Generated by Django 3.1.2 on 2020-11-28 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rapat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField()),
                ('meeting_id', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('pimpinan_rapat', models.CharField(max_length=50)),
                ('agenda', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Peserta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('nip', models.CharField(max_length=20)),
                ('jabatan', models.CharField(max_length=50)),
                ('unit_kerja', models.CharField(max_length=255)),
                ('agenda_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peserta_agenda', to='absensi.rapat')),
            ],
        ),
    ]
