# Generated by Django 3.1.2 on 2020-11-28 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peserta',
            old_name='agenda_id',
            new_name='rapat_id',
        ),
    ]
