# Generated by Django 3.1.4 on 2020-12-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0002_auto_20201129_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapat',
            name='tanggal',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Peserta',
        ),
    ]
