# Generated by Django 3.1.2 on 2021-01-28 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='tanggal_lagir',
            new_name='tanggal_lahir',
        ),
    ]
