# Generated by Django 3.1.4 on 2021-01-26 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nominatif', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pegawai',
            name='golongan',
        ),
        migrations.RemoveField(
            model_name='pegawai',
            name='jabatan',
        ),
    ]
