# Generated by Django 3.1.2 on 2021-01-03 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominatif', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golongan',
            name='pangkat',
            field=models.CharField(max_length=20),
        ),
    ]
