# Generated by Django 3.1.4 on 2021-01-26 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nominatif', '0002_auto_20210126_1121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pegawai',
        ),
    ]
