# Generated by Django 3.1.2 on 2021-01-03 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominatif', '0002_auto_20210104_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jabatan',
            name='nama',
            field=models.CharField(max_length=50),
        ),
    ]
