# Generated by Django 3.1.4 on 2021-01-26 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nominatif', '0003_delete_pegawai'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=20)),
                ('nama', models.CharField(max_length=50)),
                ('golongan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='golongan_pegawai', to='nominatif.golongan')),
            ],
        ),
    ]
