# Generated by Django 3.1.2 on 2021-01-04 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominatif', '0003_auto_20210104_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golongan',
            name='pangkat',
            field=models.CharField(max_length=30),
        ),
    ]
