# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-23 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('desc', models.TextField()),
                ('location', models.CharField(blank=True, max_length=120)),
                ('job', models.CharField(max_length=120)),
            ],
        ),
    ]
